# Generated by Django 3.0.2 on 2020-01-13 13:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received", models.DateTimeField(verbose_name="date received")),
                ("updated", models.DateTimeField(verbose_name="date updated")),
                ("email", models.EmailField(max_length=254)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("website", models.URLField()),
                (
                    "location",
                    django_countries.fields.CountryField(max_length=746, multiple=True),
                ),
                ("use_gtn", models.BooleanField()),
                ("gtn_links", models.TextField()),
                ("non_gtn_links", models.TextField()),
                ("attendance", models.TextField()),
                ("training_identifier", models.CharField(max_length=12)),
                ("advertise_eu", models.BooleanField()),
                ("other_requests", models.TextField()),
                (
                    "processed",
                    models.CharField(
                        choices=[
                            ("UN", "unprocessed"),
                            ("AP", "Approved"),
                            ("RE", "Rejected"),
                        ],
                        default="UN",
                        max_length=2,
                    ),
                ),
            ],
        )
    ]
