# Generated by Django 3.0.2 on 2020-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("training", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="training", name="gtn_links", field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name="training",
            name="non_gtn_links",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="other_requests",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="training", name="website", field=models.URLField(blank=True)
        ),
    ]
