# Generated by Django 3.0.2 on 2020-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200113_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='received',
            field=models.DateField(verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='training',
            name='updated',
            field=models.DateField(verbose_name='date updated'),
        ),
    ]
