# Generated by Django 3.0.2 on 2020-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200113_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='Hi', max_length=64),
            preserve_default=False,
        ),
    ]
