# Generated by Django 3.0.2 on 2020-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='advertise_eu',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='training',
            name='use_gtn',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
