# Generated by Django 3.0.2 on 2020-01-13 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20200113_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='updated',
        ),
        migrations.AlterField(
            model_name='training',
            name='received',
            field=models.DateField(default=datetime.date.today, verbose_name='date received'),
        ),
    ]
