# Generated by Django 3.0.3 on 2020-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20200113_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_identifier',
            field=models.CharField(max_length=20),
        ),
    ]
