# Generated by Django 3.0.3 on 2020-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20200213_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='blogpost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='retain_contact',
            field=models.BooleanField(default=False),
        ),
    ]
