# Generated by Django 3.1.13 on 2022-03-28 22:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20200225_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='advertise_eu',
            new_name='advertise',
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
