# Generated by Django 3.1.3 on 2020-11-24 21:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20200225_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_identifier',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_identifier', message='Training identifier contains illegal characters', regex=re.compile('^[-a-z0-9_]+$'))]),
        ),
    ]
