# Generated by Django 3.1.13 on 2022-04-26 22:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20220328_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
