# Generated by Django 3.1.13 on 2022-09-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20201124_2102'),
        ('training', '0011_auto_20220426_2252'),
    ]

    operations = [
    ]
